### PR TITLE
Upgrade to hijackresponse 5

### PR DESCRIPTION
**Pull request by gustavnikolaj**
Using the proposed api from: https://github.com/gustavnikolaj/hijackresponse/pull/24

### CODE REVIEW

**Comment by gustavnikolaj** [comment]
@papandreou the first commit failed CI but only due to lint. I fixed that in a separate commit as basically the whole file was changed by prettier, making it impossible to review the actual diff. If you want to look at this, look at the commit that is not about formatting :-)

**Comment by gustavnikolaj** [comment]
The latest commit updates to the first pre-release of v5. It also removes the err argument to the callback.

**Comment by papandreou** [comment]
Same here, looks good!

**Review by papandreou — APPROVED** [review]
LGTM 🚀

**Comment by papandreou** [comment]
Released in 4.2.0.

**Pull request merged**
